# ci.yml
name: CI

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: pr-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with: { version: 10 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm run --if-present lint
      - run: pnpm run --if-present knip
      - run: pnpm run --if-present typecheck
      - run: pnpm run --if-present test
      - run: pnpm run --if-present build
