name: CI
on:
  pull_request:
    branches: [main]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Detect if package.json version was bumped
      - id: vc
        uses: EndBug/version-check@v2
        with:
          diff-search: true  # Check the diff, not only commit message

      # Fail if version was not bumped
      - name: Fail if version not bumped
        if: steps.vc.outputs.changed != 'true'
        run: |
          echo "::error::This PR must bump package.json version."
          exit 1

  build-and-test:
    needs: check-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm run --if-present lint
      - run: pnpm run --if-present typecheck
      - run: pnpm run --if-present test
      - run: pnpm run build
