name: Pages & Release on main

on:
  push:
    branches: [ main ]

concurrency:
  group: main-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  pages:
    name: Build & Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build   # build output → ./dist

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # optional
          force_orphan: true   # create branch historyless (cleaner)

  release:
    name: Release if version is unreleased
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          CURR="v$(jq -r .version package.json)"
          echo "Current version: $CURR"

          if gh release view "$CURR" >/dev/null 2>&1; then
            echo "Release $CURR already exists. Skipping."
            exit 0
          fi

          echo "Creating release $CURR"
          gh release create "$CURR" --title "$CURR" --generate-notes
